<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <Prefer32Bit>false</Prefer32Bit>
    <RootNamespace>SeqxcToolset</RootNamespace>
    <AssemblyName>Seqxc Toolset</AssemblyName>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>
</Project>
